{{- if .Values.image.pullSecretEncrypted }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.image.pullSecretEncrypted }}
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
