replicaCount: 1

image:
  repository: ghcr.io/jcrlabs/blog-front
  pullPolicy: IfNotPresent
  tag: ""
  pullSecretName: ghcr-pull-secret

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  host: ""
  tls: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi

hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env:
  API_URL: ""
